name = "communities"
main = "src/index.ts"
compatibility_date = "2023-01-25"
keep_vars = true
node_compat = true

routes = [
	{ pattern = "communities.lenshareapp.xyz", custom_domain = true }
]

[placement]
mode = "smart"

[env.production.vars]
CLICKHOUSE_REST_ENDPOINT = "https://rv2yfwfigr.eu-west-1.aws.clickhouse.cloud:8443"
