name = "sts"
main = "src/index.ts"
compatibility_date = "2023-01-25"
routes = [
	{ pattern = "sts.lenshareapp.xyz", custom_domain = true }
]
keep_vars = true

[env.production.vars]
EVER_ACCESS_KEY = "a586ebe80de1407eb39fa635b965f42e"
EVER_ACCESS_SECRET = "fV1ZjYmfNP6hMRiAzUwnFy8eCNrg7l88a5eW7tJ3"