name = "metadata"
main = "src/index.ts"
compatibility_date = "2023-01-25"
keep_vars = true


routes = [
	{ pattern = "metadata.lenshareapp.xyz", custom_domain = true }
]

[placement]
mode = "smart"

[env.production.vars]
BUNDLR_PRIVATE_KEY = "db883d317f6e229007412eae99aee86709ffdf05822220cb0db6f360008982ed"
HUGGINGFACE_API_KEY = "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"
