name = "metadataok"
main = "src/index.ts"
compatibility_date = "2023-01-25"
routes = [
	{ pattern = "meta.lenshareapp.xyz", custom_domain = true }
]
keep_vars = true
node_compat = true

[env.production.vars]
BUNDLR_PRIVATE_KEY = "3196d81e4243f92a61dff2f88df774a6ce8ce2d183375365ec1dec2034812170"
